#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
- name: andrey
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOHSYLPTz2x6JRNMG9853eZ7GCD8HaoU2HAWrxcaIgr2
- name: cloud-user
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOHSYLPTz2x6JRNMG9853eZ7GCD8HaoU2HAWrxcaIgr2
runcmd: []

