---
- name: Deploy loadbalancer
  become: true
  hosts: frontend

  tasks:
  - name: Install nginx
    dnf:
      name: nginx
      state: present

  - name: Copy config
    template:
      src: ../templates/balance-rr.conf.j2
      dest: /etc/nginx/conf.d/balance-rr.conf

  - name: "Enable nginx"
    systemd:
      name: "nginx"
      state: "started"
      enabled: true
 
       
