- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
