---
- name: "Make GFS2 filesystem"
  become: true
  hosts: pcs_master

  tasks:
  - name: Format the volumes with a GFS2 file system
    shell: "echo 'y' | mkfs.gfs2 -j3 -p lock_dlm -t skynet:gfs2 /dev/shared_vg/shared_lv"

  - name: Waiting 10 sec...
    pause:
      seconds: 10
