---
- hosts: localhost
  become: true
  tasks:
  - name: "Install nginx"
    yum:
      name: "nginx"
      state: "latest"
  
  - name: "Enable nginx"
    systemd:
      name: "nginx"
      state: "started" 
