- name: Install nginx
  dnf:
    name: nginx
    state: present

- name: Install curl
  dnf:
    name: curl
    state: present

- name: Copy config
  template:
    src: balance-rr.conf.j2
    dest: /etc/nginx/conf.d/balance-rr.conf

- name: "Enable nginx"
  systemd:
    name: "nginx"
    state: "started"
    enabled: true
