---
- name: Copy database dump file
  copy:
    src: userdata.dump
    dest: /tmp

- name: Enable dnf module postgresql
  command: "dnf module enable postgresql:15 -y"

- name: Install postgresql client
  dnf:
    name: postgresql
    state: present

- name: create db
  shell: "psql postgres://postgres:postgres@10.0.0.10:5000 -c 'create database userdata;'"

- name: restore db
  shell: "psql postgres://postgres:postgres@10.0.0.10:5000/userdata < /tmp/userdata.dump"
