- name: install packages
  become: true
  dnf:
    name: "iscsi-initiator-utils"
    state: "present"

- name: Touch initiatorname.iscsi
  file:
    path: /etc/iscsi/initiatorname.iscsi
    state: touch
    owner: root
    group: root
    mode: 0600

- name: Configuring initiatorname.iscsi on web1
  lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    #regexp: '^InitiatorName='
    line: InitiatorName=iqn.2024-10.my.project:web1
  when:
    ansible_hostname == 'web1'
  notify: restart iscsid

- name: Configuring initiatorname.iscsi on web2
  lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    #regexp: '^InitiatorName='
    line: InitiatorName=iqn.2024-10.my.project:web2
  when:
    ansible_hostname == 'web2'
  notify: restart iscsid

- name: Configuring initiatorname.iscsi on web3
  lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    #regexp: '^InitiatorName='
    line: InitiatorName=iqn.2024-10.my.project:web3
  when:
    ansible_hostname == 'web3'
  notify: restart iscsid

- name: Add target first
  command: iscsiadm -m discoverydb -t st -p 10.0.0.13 -o new

- name: Discover first target
  command: iscsiadm -m discoverydb -t sendtargets -p 10.0.0.13 --discover

- name: Add target second
  command: iscsiadm -m discoverydb -t st -p 10.0.0.60 -o new

- name: Discover second target
  command: iscsiadm -m discoverydb -t sendtargets -p 10.0.0.60 --discover

- name: Target login
  command: iscsiadm -m node -T iqn.2024-10.my.project -l

- name: Enable iscsid
  systemd:
    name: iscsi
    state: started
    enabled: true
