---
- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Install software
  dnf:
    name:
      - nginx
    state: present

- name: Add tmpcl
  template:
    src: loadbalancer.ctmpl.j2
    dest: /etc/nginx/conf.d/loadbalancer.ctmpl
  notify: reload consul-template

- name: Add balancer conf
  template:
    src: loadbalancer.conf.j2
    dest: /etc/nginx/conf.d/loadbalancer.conf

- name: "Enable nginx"
  systemd:
    name: "nginx"
    state: "started"
    enabled: true
