- name: Add physical volume 
  command: "pvcreate /dev/mapper/disk5G"
  when: "ansible_hostname == 'web1'"

- name: Add /dev/mapper/disk5G to shared volume group
  lvg:
    vg: shared_vg
    pvs: /dev/mapper/disk5G
    vg_options: "--shared"
  when: ansible_hostname == 'web1'

- name: add the shared devices to the devices file
  command: "lvmdevices --adddev /dev/mapper/disk5G"

- name: Start the lock manager for shared volume group
  command: "vgchange --lockstart shared_vg"

- name: Create the shared logical volumes
  lvol:
    vg: shared_vg
    lv: shared_lv
    size: 4096m
    opts: --activate sy
  when: ansible_hostname == 'web1'
